config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root 'feed_events#index'
  
  resources :user_profiles
  resources :genres
  resources :events
  resources :comments
  
  post 'event_response', to: 'user_event_responses#update', as: :event_response
  
  get 'reactivate_account', to: 'user_profiles#reactivate_account', as: :reactivate_account
  get 'activate_user', to: 'user_profiles#activate_user', as: :activate_user
  get 'remove_event', to: 'events#remove_from_feed', as: :remove_event
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  
  # Setting domain specific primary key
  self.primary_key = 'user_id'
  
  # Model associations
  belongs_to :user
  belongs_to :location
  accepts_nested_attributes_for :location
  
  # ActiveRecord Validations
    validates :first_name, presence: true, length: { minimum: 1, maximum: 255 }
    validates :last_name, presence: true, length: { minimum: 1, maximum: 255 }
    validates :birth_date, presence: true
    validates_datetime :birth_date, :before => :now
    validates_datetime :birth_date, :after => lambda { 150.years.ago }
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
    before_action :authenticate_user!
    before_action :profile_doesnt_exist, only: [:new, :create]
    before_action :profile_exists, only: [:show, :update, :destroy, :edit]
    before_action :profile_active?, except: [:activate_user, :reactivate_account]
    
    def new
        @user_profile = UserProfile.new
        @user_profile.build_location
    end
    
    def create
        @user_profile = current_user.build_user_profile(user_profile_params.except(:location_attributes, :location_component_attributes))
        
        location_attributes = user_profile_params[:location_attributes]
        lat = location_attributes[:lat].to_d.round(8)
        lng = location_attributes[:lng].to_d.round(8)
        
        # Now I can build the locations by hand
        if Location.exists?(:lat => lat, :lng => lng)
            
            @user_location = Location.find_by(:lat => lat, :lng => lng)
            @user_profile.location_id = @user_location.id
        else
            @user_location = Location.create(:lat => lat, :lng => lng)
            @user_profile.location_id = @user_location.id
            
            user_components = user_profile_params[:location_component_attributes]
            user_components.each do |component, value|
               @user_location.location_components.create(:component_type => value[:component_type], :value => value[:value])  
            end
        end
        
        if @user_profile.save
            redirect_to root_url
        else
           render 'new' 
        end
    end
    
    def show 
       @user_profile = UserProfile.find(params[:id]) 
    end
    
    def edit
       @user_profile = UserProfile.find(params[:id])
    end
    
    def update
        @user = UserProfile.find(params[:id])
        
        update_params = user_profile_params.except(:location_attributes, :location_component_attributes)
        location_attributes = user_profile_params[:location_attributes]
        lat = location_attributes[:lat].to_d.round(8)
        lng = location_attributes[:lng].to_d.round(8)
        
        if Location.exists?(:lat => lat, :lng => lng)
            user_location = Location.find_by(:lat => lat, :lng => lng)
            update_params[:location_id] = user_location.id
        else
            user_location = Location.create(:lat => lat, :lng => lng)
            update_params[:location_id] = user_location.id
            
            location_components = user_profile_params[:location_component_attributes]
            location_components.each do |component, value|
               user_location.location_components.create(:component_type => value[:component_type], :value => value[:value])  
            end
        end
        
        if @user.update_attributes(update_params)
            redirect_to root_url
        else
          render 'edit'
        end
    end
    
    def destroy
       @user = UserProfile.find(params[:id])
       @user.update(active: false)
       sign_out current_user
       redirect_to root_url
    end
    
    def reactivate_account
       render 'reactivate_account' 
    end
    
    def activate_user
        #This is the method that sets user activated
        @user = UserProfile.find(params[:id])
        @user.update(active: true)
        redirect_to root_url
    end
    
    private
    
        def profile_exists
            unless UserProfile.exists?(user_id: current_user)
                redirect_to new_user_profile_path
            end
        end
        
        def profile_doesnt_exist
           if UserProfile.exists?(user_id: current_user)
                redirect_to root_url
            end
        end
    
        def user_profile_params
            params.require(:user_profile).permit(:first_name, :last_name, :birth_date, location_attributes: [:id, :lat, :lng], location_component_attributes: [:id, :component_type, :value])
        end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/edit.html.erb
<div class="container create-profile">
    <div class="card-padder">
        <div class="card">
        
            <h1>Update Your Profile</h1>
            
            <% if @user_profile.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@user_profile.errors.count, "error") %> prohibited this article from being saved:</h2>
                
                    <ul>
                        <% @user_profile.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            
            <%= form_for(@user_profile) do |f| %>
                <div class="form-container">
                    <%= f.label :first_name %>
                    <%= f.text_field :first_name %>
                </div>
                
                <div class="form-container">
                    <%= f.label :last_name %>
                    <%= f.text_field :last_name %>
                </div>
                
                <div class="form-container">
                    <%= f.label :birth_date %>
                    <%= f.date_field :birth_date %>
                </div>
                
                <div class="form-container">
                  <%= label_tag(:address, "Address") %>
                  <%= text_field_tag(:address) %>
                  <ul id="addressList"></ul>
                  
                    <%= f.fields_for :location do |f_location| %>
                    
                        <%= f_location.hidden_field :lat %>
                        <%= f_location.hidden_field :lng %>
                        
                    <% end %>
                </div>
            
                <%= f.submit "Update Profile" %>
            <% end %>
        </div>
    </div>
</div>




<script>
  
  
// Location functions

var inputTimeout;
var addressSelected = 0;


$('#address').on('input keyDown', function() {
    clearTimeout(inputTimeout);
    inputTimeout = setTimeout(function() {checkAddressData('address');},500);
});

function checkAddressData(aim) {
    var geocoder = new google.maps.Geocoder(),
    addressDataTemp = {},
    map,
    formattedResult,
    addressComponents,
    lat,
    lng,
    address =$('#' + aim).val(),
    appendText = '';
    addressSelected = 0;
    
    if (address != '') {
        geocoder.geocode({'address': address}, function(results, status) {
            console.log(status);
            if(status == 'OK'){
                $.each(results, function(index,value) {
                    appendText += '<li class="popUpList" id="item_' + index + '">' + value['formatted_address'] + '</li>';
                });
            } else {
                appendText = '0 Results found, please use a different address';
                console.log(status);
            }
            $('#addressList').html(appendText);
            $('#addressList').show();
            $('.popUpList').unbind();
            $('.popUpList').on('click touch', function() {
                $('#addressList').hide();
                addressSelected = 1;
                var thisItem = $(this).attr('id').split('_')[1];
                var thisAddress = results[thisItem];
                console.log(thisAddress);
                formattedResult = thisAddress['formatted_address'];
                addressComponents = thisAddress['address_components'];
                var formElement = '<input type="hidden" name="user_profile[location_component_attributes][0][component_type]" id="user_profile_location_component_attributes_0_component_type" value="formatted_address" />'
                formElement += '<input type="hidden" name="user_profile[location_component_attributes][0][value]" id="user_profile_location_component_attributes_0_value" value="' + formattedResult + '" />'
                $('#user_profile_location_attributes_lng').after(formElement);
                $.each(addressComponents, function(i){
                    var formElement = '<input type="hidden" name="user_profile[location_component_attributes][' + (i+1) + '][component_type]" id="user_profile_location_component_attributes_' + (i+1) + '_component_type" value="' + this.types[0] + '" />'
                    formElement += '<input type="hidden" name="user_profile[location_component_attributes][' + (i+1) + '][value]" id="user_profile_location_component_attributes_' + (i+1) + '_value" value="' + this.long_name + '" />'
                    $('#user_profile_location_attributes_lng').after(formElement);
                });
                lat = thisAddress['geometry']['location']['lat'];
                lng = thisAddress['geometry']['location']['lng'];
                $('#user_profile_location_attributes_lat').val(lat);
                $('#user_profile_location_attributes_lng').val(lng);
                $('#' + aim).val(formattedResult);
                $('#mapFrame').html('<iframe src="https://maps.google.com/maps?&q=' + formattedResult + '&output=embed"></iframe>');
            });
        });
    } else {
        $('.popUpList').unbind();
        $('#addressList').hide();
    }
}
    
$('#closeButton').on('click touch', function() {
    $('#modal').hide();
});
    
$('form').submit(function(event) {
    if (addressSelected != 1){
        event.preventDefault();
        $('#error').html('Please select one of the formatted addresses');
        $('#error').show();
    }
});
  
</script>

app/views/user_profiles/new.html.erb
<div class="container create-profile">
    <div class="card-padder">
        <div class="card">
        
            <h1>Create Your Profile</h1>
            
            <% if @user_profile.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(@user_profile.errors.count, "error") %> prohibited this article from being saved:</h2>
                
                    <ul>
                        <% @user_profile.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            
            <%= form_for(@user_profile) do |f| %>
                <div class="form-container">
                    <%= f.label :first_name %>
                    <%= f.text_field :first_name %>
                </div>
                
                <div class="form-container">
                    <%= f.label :last_name %>
                    <%= f.text_field :last_name %>
                </div>
                
                <div class="form-container">
                    <%= f.label :birth_date %>
                    <%= f.date_field :birth_date %>
                </div>
                
                <div class="form-container">
                  <%= label_tag(:address, "Address") %>
                  <%= text_field_tag(:address) %>
                  <ul id="addressList"></ul>
                  
                    <%= f.fields_for :location do |f_location| %>
                    
                        <%= f_location.hidden_field :lat %>
                        <%= f_location.hidden_field :lng %>
                        
                    <% end %>
                </div>
            
                <%= f.submit "Update Profile" %>
            <% end %>
        </div>
    </div>
</div>



<script>
  
  
// Location functions

var inputTimeout;
var addressSelected = 0;


$('#address').on('input keyDown', function() {
    clearTimeout(inputTimeout);
    inputTimeout = setTimeout(function() {checkAddressData('address');},500);
});

function checkAddressData(aim) {
    var geocoder = new google.maps.Geocoder(),
    addressDataTemp = {},
    map,
    formattedResult,
    addressComponents,
    lat,
    lng,
    address =$('#' + aim).val(),
    appendText = '';
    addressSelected = 0;
    
    if (address != '') {
        geocoder.geocode({'address': address}, function(results, status) {
            console.log(status);
            if(status == 'OK'){
                $.each(results, function(index,value) {
                    appendText += '<li class="popUpList" id="item_' + index + '">' + value['formatted_address'] + '</li>';
                });
            } else {
                appendText = '0 Results found, please use a different address';
                console.log(status);
            }
            $('#addressList').html(appendText);
            $('#addressList').show();
            $('.popUpList').unbind();
            $('.popUpList').on('click touch', function() {
                $('#addressList').hide();
                addressSelected = 1;
                var thisItem = $(this).attr('id').split('_')[1];
                var thisAddress = results[thisItem];
                console.log(thisAddress);
                formattedResult = thisAddress['formatted_address'];
                addressComponents = thisAddress['address_components'];
                var formElement = '<input type="hidden" name="user_profile[location_component_attributes][0][component_type]" id="user_profile_location_component_attributes_0_component_type" value="formatted_address" />'
                formElement += '<input type="hidden" name="user_profile[location_component_attributes][0][value]" id="user_profile_location_component_attributes_0_value" value="' + formattedResult + '" />'
                $('#user_profile_location_attributes_lng').after(formElement);
                $.each(addressComponents, function(i){
                    var formElement = '<input type="hidden" name="user_profile[location_component_attributes][' + (i+1) + '][component_type]" id="user_profile_location_component_attributes_' + (i+1) + '_component_type" value="' + this.types[0] + '" />'
                    formElement += '<input type="hidden" name="user_profile[location_component_attributes][' + (i+1) + '][value]" id="user_profile_location_component_attributes_' + (i+1) + '_value" value="' + this.long_name + '" />'
                    $('#user_profile_location_attributes_lng').after(formElement);
                });
                lat = thisAddress['geometry']['location']['lat'];
                lng = thisAddress['geometry']['location']['lng'];
                $('#user_profile_location_attributes_lat').val(lat);
                $('#user_profile_location_attributes_lng').val(lng);
                $('#' + aim).val(formattedResult);
                $('#mapFrame').html('<iframe src="https://maps.google.com/maps?&q=' + formattedResult + '&output=embed"></iframe>');
            });
        });
    } else {
        $('.popUpList').unbind();
        $('#addressList').hide();
    }
}
    
$('#closeButton').on('click touch', function() {
    $('#modal').hide();
});
    
$('form').submit(function(event) {
    if (addressSelected != 1){
        event.preventDefault();
        $('#error').html('Please select one of the formatted addresses');
        $('#error').show();
    }
});
  
</script>

app/views/user_profiles/reactivate_account.html.erb
<div class="container user-profile">
    <div class="card-padder">
        <div class="card">
            
            <h4>Your account is currently inactive</h4>
            <%= link_to "Reactivate now", activate_user_path(:id => current_user.id) %>
            
        </div>
    </div>
</div>

app/views/user_profiles/show.html.erb
<div class="container user-profile">
    <div class="card-padder">
        <div class="card">
            
            <h2><%= @user_profile.first_name %> <%= @user_profile.last_name %>'s Profile</h2>
            
            <div class="profile-info">
                <h4>Personal Information</h2>
                <p>Email: <%= @user_profile.user.email %></p>
                <p>Birth Date: <%= @user_profile.birth_date.strftime("%B %d, %Y") %></p>
                <p>Location: <%= "#{@user_profile.location.location_components.where(:component_type => 'formatted_address').first.value}" %></p>
                <div class="horizontal-divider"></div>
                <h4>Interests</h2>
                <% @user_profile.user.genres.each do |genre| %>
                    <p><%= genre.name %></p>
                <% end %>
            </div>
            
            <%= link_to "Edit Profile", edit_user_profile_path(current_user) %>
            <%= link_to "Deactivate Profile", user_profile_path, method: :delete %>
        </div>
    </div>
</div>