config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root 'feed_events#index'
  
  resources :user_profiles
  resources :genres
  resources :events
  resources :comments
  
  post 'event_response', to: 'user_event_responses#update', as: :event_response
  
  get 'reactivate_account', to: 'user_profiles#reactivate_account', as: :reactivate_account
  get 'activate_user', to: 'user_profiles#activate_user', as: :activate_user
  get 'remove_event', to: 'events#remove_from_feed', as: :remove_event
end

app/models/feed_event.rb
class FeedEvent < ActiveRecord::Base
   self.primary_key = "event_id"
   
   belongs_to :event
end

app/controllers/feed_events_controller.rb
class FeedEventsController < ApplicationController
    before_action :authenticate_user!
    before_action :profile_active?
    
    def index
        @events = FeedEvent.all
        @new_comment = Comment.new
        @all_comments = Comment.all
        
        @comments = Array.new
        
        @all_comments.each do |comment, i|
            new_comment = {comment: comment.comment, event: "#{comment.event_id}", creator: "#{comment.creator.user_profile.first_name} #{comment.creator.user_profile.last_name}" } 
            @comments << new_comment
        end
    end
end

app/views/feed_events/_ad.html.erb
<div class="card-padder">
    <div class="card ad">
        <h2>This is an ad</h2>
        <p>This is content for an ad!</p>
    </div>
</div>

app/views/feed_events/_event_info.html.erb
<section class="inset card" id="template">
    <div class="info-container">
        <div class="event-info">
            <div class="event-head">
                <div class="feature-image"></div>
                <div class="bg-overlay"></div>
                
                <div class="general-info">
                    <h2 class="event-name"></h2>
                    <p class="medium event-host">Hosted by <span class="highlight"></span></p>
                    <span class="over-eighteen medium"></span>
                </div>
            </div>
            
            <div class="event-body">
                <div class="info-inner">
                    <div class="info-left">
                        <p class="event-date"></p>
                        <p class="event-location"></p>
                    </div>
                    
                    <div class="info-right">
                        <p class="event-genres"></p>
                    </div>
                </div>
                
                <div class="rsvp">
                    <%= form_tag({controller: "user_event_responses", action: "update"}, method: "post", class: "rsvp-going") do %>
                    <% end %>
                    
                    <%= form_tag({controller: "user_event_responses", action: "update"}, method: "post", class: "rsvp-interested") do %>
                    <% end %>
                    
                    <%= form_tag({controller: "user_event_responses", action: "update"}, method: "post", class: "rsvp-remove") do %>
                    <% end %>
                </div>
                
                <div class="description">
                    <p></p>
                </div>
            </div>
        </div>
        
        <div class="event-comments">
            <div class="comment-input">
                <%= form_for Comment.new, method: :post do |f| %>
                    <%= f.hidden_field :event_id %>
                    <%= f.label :comment %>
                    <%= f.text_area :comment %>
                    <%= f.submit "Post Comment" %>
                <% end %>
			</div>
			
			<div class="horizontal-divider"></div>
			
			<div class="comments">
				<p id="no-comments">There are no comments about this event.</p>
			</div>
        </div>
    </div>
</section>

app/views/feed_events/_events_feed.html.erb
<% unless @events.third.nil? %>
    <% @events[2..-1].each_with_index do |event, i| %>
        <% i+=4 %>
        <%= render :partial => "feed_events/feed_event", :locals => {:event => event, :event_count => i} %>
    <% end %>
<% end %>

app/views/feed_events/_feed_event.html.erb
<div class="card-padder">
    <%= content_tag :article, class: "card event", id: "event-#{event.event_id}", 'data-order' => event_count, style: "background-image: url(#{event.feature_image_path})" do %>
        <div class="image-overlay"></div>
        <div class="dropdown">
            <a href="#">
                <%= image_tag('icons/menu.png') %>
            </a>
            <ul>
                <li>
                    <%= link_to remove_event_path(:id => event.event_id) do %>
                        <span>Remove From Feed</span>
                    <% end %>
                </li>
                <% if event.creator_id == current_user.id %>
                    <div class="horizontal-divider"></div>
                    <li>
                        <%= link_to edit_event_path(event.event_id) do %>
                            <span>Edit Event</span>
                        <% end %>
                    </li>
                    <div class="horizontal-divider"></div>
                    <li>
                        <%= link_to event_path(:id => event.event_id), method: :delete, data: { confirm: "Event cancellations can not be reversed. Are you sure?" } do %>
                            <span>Cancel Event</span>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
        <div class="info-container">
            <div class="date">
                <span class="year"><%= event.event_start.year %></span>
                <span class="month"><%= event.event_start.strftime("%d %b") %></span>
            </div>
            
            <div class="front-info">
                <h2><%= event.event_name %></h2>
                <p><%= "#{event.event.location_components.where(:component_type => 'formatted_address').first.value}" %></p>
                <%= genre_display(event.event.genres) %>
            </div>
        </div>
        <button class="medium more-information" id="more-<%= event.event_id %>" data-order="<%= event_count %>">More Information</button>
    <% end %>
</div>

app/views/feed_events/_first_row.html.erb
<div class="row">
    
        <%= render :partial => "feed_events/top_event", :locals => {:event => @events[0]} %>
        
        <% if @events.second %>
                <%= render :partial => "feed_events/feed_event", :locals => {:event => @events[1], :event_count => 3} %>
        <% end %>
        
        <%= render "feed_events/ad" %>
</div>

app/views/feed_events/_top_event.html.erb
<div class="card-padder">
    <%= content_tag :article, class: "card event", id: "event-#{event.event_id}", 'data-order' => "1", style: "background-image: url(#{event.feature_image_path})" do %>
        <div class="image-overlay"></div>
        <div class="dropdown">
            <a href="#">
                <%= image_tag('icons/menu.png') %>
            </a>
            <ul>
                <li>
                    <%= link_to remove_event_path(:id => event.event_id) do %>
                        <span>Remove From Feed</span>
                    <% end %>
                </li>
                <% if event.creator_id == current_user.id %>
                    <div class="horizontal-divider"></div>
                    <li>
                        <%= link_to edit_event_path(event.event_id) do %>
                            <span>Edit Event</span>
                        <% end %>
                    </li>
                    <div class="horizontal-divider"></div>
                    <li>
                        <%= link_to event_path(:id => event.event_id), method: :delete, data: { confirm: "Event cancellations can not be reversed. Are you sure?" } do %>
                            <span>Cancel Event</span>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
        <div class="info-container">
            <div class="date small">
                <span class="year"><%= event.event_start.year %></span>
                <span class="month"><%= event.event_start.strftime("%d %b") %></span>
            </div>
            
            <div class="front-info">
                <div class="info-above">
                    <h2><%= event.event_name %></h2>
                    <p class="medium">Hosted by <span class="highlight"><%= "#{event.creator_first_name} #{event.creator_last_name}" %></span></p>
                    <%= over_eighteen_display(event.over_eighteen) %>
                </div>
                
                <div class="info-left">
                    <p class="medium"><%= "#{event.event_start.to_formatted_s(:long)} to #{event.event_end.to_formatted_s(:long)}" %><p>
                    <p><%= "#{event.event.location_components.where(:component_type => 'formatted_address').first.value}" %></p>
                </div>
                
                <div class="info-right">
                    <%= genre_display(event.event.genres.all) %>
                </div>
                
                <div class="info-bottom large">
                    <p><%= event.event_description %></p>
                </div>
            </div>
            <button class="medium more-information" id="more-<%= event.event_id %>" data-order="1">More Information</button>
        </div>
    <% end %>
</div>

app/views/feed_events/index.html.erb
<div class="container feed">
    <% if @events.first.nil? %>
        There are no events to display.
    <% else %>
        <%= render 'feed_events/event_info' %>
        <%= render 'feed_events/first_row' %>
        <%= render 'feed_events/events_feed' %>
    <% end %>
</div>


<script>
    var currentViewed = 0;
    
    //checks window breakpoint
    function checkSize(){
        if ($(".card-padder .card.event .medium").css("display") == "none" ){
            var size = "small";
        } else if ($(".card-padder .card.event .large").css("display") == "none"){
            var size = "medium";
        } else {
            var size = "large";
        }
        return size;
    }
    
    function formatDate(date) {
        var hours = date.getHours();
        var minutes = date.getMinutes();
        var ampm = hours >= 12 ? 'pm' : 'am';
        hours = hours % 12;
        hours = hours ? hours : 12; // the hour '0' should be '12'
        minutes = minutes < 10 ? '0'+minutes : minutes;
        var strTime = hours + ':' + minutes + ' ' + ampm;//to show time
        return date.getDate() + "/" + date.getMonth() + "/" + date.getFullYear() + " at " + strTime;
    }
    
    function createButton(event_id, response, button) {
        if (button == response){
            var button_output = '<input type="hidden" value="' + event_id + '" name="response[event_id]" id="response_event_id" />'
            button_output += '<input type="hidden" value="none" name="response[response_id]" id="response_response_id" />'
            button_output += '<input type="submit" name="commit" value="' + button + '" class="active" />'
        } else {
            var button_output = '<input type="hidden" value="' + event_id + '" name="response[event_id]" id="response_event_id" />'
            button_output += '<input type="hidden" value="' + button + '" name="response[response_id]" id="response_response_id" />'
            button_output += '<input type="submit" name="commit" value="' + button + '" />'
        }
        return button_output
    }


    // Rewrites events JS Object to index by event_id
    var temp_events = <%= raw @events.to_json %>
    var events = {};
    
    $.each(temp_events, function(id,val){
        events[val.event_id] = val;
    });
    
    var comments = <%= raw @comments.to_json %>;
    comments.reverse();
    
    console.log(comments);
    
    
    
    /*$('.moreBtn').on('click touch', function() {
        Normal notation
    }); */
    
    
    function aggregateInfo (events, id) {
        
        console.log('aggregate');
        console.log(events[id]);
        
        $('#current .feature-image').css("background-image", "url("+events[id].feature_image_path+")");
        $('#current .event-name').html(events[id].event_name);
        $('#current .event-host .highlight').html(events[id].creator_first_name + ' ' + events[id].creator_last_name);
        if(events[id].over_eighteen != false){
            $('#current .over-eighteen').html("18+");
        }
        var d = new Date(events[id].event_start);
        var e = formatDate(d);
        $('#current .event-date').html(e);
        
        $('#current .event-location').html(events[id].event_address);
        $('#current .description p').html(events[id].event_description);
        $('#current .event-genres').html(events[id].event_genre);
        
        $('#current #comment_event_id').val(events[id].event_id);
        
        $('#current .rsvp-going').append(createButton(events[id].event_id, events[id].user_response, "going"));
        $('#current .rsvp-interested').append(createButton(events[id].event_id, events[id].user_response, "interested"));
        $('#current .rsvp-remove').append(createButton(events[id].event_id, events[id].user_response, "remove"));
        
        var comment_event_id = events[id].event_id;
        $.each(comments, function(id){
            if(comments[id].event == comment_event_id){
                $('#current #no-comments').remove();
                var the_comment = '<div class="comment">';
                the_comment += '<h5>' + comments[id].creator + '</h5>';
                the_comment += '<p>' + comments[id].comment + '</p>'
                the_comment += '</div>';
                the_comment += '<div class="horizontal-divider"></div>';
                $('#current .comments').append(the_comment);
            }
        });
        
        var event_genres = events[id].event_genres;
        var genres = "<h5>Genres</h5>"
        $.each(event_genres, function(id){
            console.log(event_genres[id]);
            genres += '<p>' + event_genres[id] + '</p>'
        });
        
        $('#current .info-right').append(genres);
        
        
        currentViewed = id;
        setTimeout(function() {
            $('#current').css("max-height","1000px");
        },0);
    }
    
    
    function showInfoLarge (thisObject, order, events, id){
        console.log('showinfo');
        var template = $("#template").html();
        if(order < 4){
            $('.row').after('<section class="inset card" id="current">' + template + '</section>');
        } else if(order%3 != 0){
            var row = Math.floor(order / 3);
            if ($('.card.event[data-order='+parseInt((row *3)+3)+']').length) {
                $('.card.event[data-order='+parseInt((row *3)+3)+']').parent().after('<section class="inset card" id="current">' + template + '</section>');
            } else if ($('.card.event[data-order='+parseInt((row *3)+2)+']').length) {
                $('.card.event[data-order='+parseInt((row *3)+2)+']').parent().after('<section class="inset card" id="current">' + template + '</section>');
            } else {
                $(thisObject).parent().after('<section class="inset card" id="current">' + template + '</section>');
            }
        } else {
            $(thisObject).parent().parent().after('<section class="inset card" id="current">' + template + '</section>');
        } 
        aggregateInfo(events, id);
    }
    
    function showInfoMedium (thisObject, order, events, id) {
        var template = $("#template").html();
        if(order < 4){
            $('.row').after('<section class="inset card" id="current">' + template + '</section>');
        } else if(order%2 == 0){
            $(thisObject).parent().parent().next().after('<section class="inset card" id="current">' + template + '</section>');
            
        } else {
            $(thisObject).parent().parent().after('<section class="inset card" id="current">' + template + '</section>');
        }
         aggregateInfo(events, id);
    }
    
    function showInfoSmall (thisObject, events, id) {
        var template = $("#template").html();
        $(thisObject).parent().after('<section class="inset card" id="current">' + template + '</section>');
         aggregateInfo(events, id);
    }
    
    
    
    
    
    
    $(document).on('click touch', '.more-information', function() {
        var order = $(this).attr('data-order');
        var id = $(this).attr('id').split('-')[1];
        var breakpoint = checkSize();
        
        var thisObject = this;
        if (currentViewed == id) {
            $('#current').css("max-height","0");
            currentViewed = 0;
            setTimeout(function() {
                    $('#current').remove();
            },1000);
        } else {
            if ($('#current').length > 0) {
                $('#current').css("max-height","0");
                setTimeout(function() {
                    $('#current').remove();
                    if (breakpoint == 'large'){
                        showInfoLarge(thisObject, order, events, id);
                    } else {
                        showInfoMedium(thisObject, order, events, id);
                    }
                },1000);
            } else {
                if (breakpoint == 'large'){
                    showInfoLarge(thisObject, order, events, id);
                } else {
                    showInfoMedium(thisObject, order, events, id);
                }
            }
        }
    
    });
    
    $(document).on('click touch', '.card.event', function() {
        var template = $("#template").html();
        var id = $(this).attr('id').split('-')[1];
        var breakpoint = checkSize();
        console.log('I AM THE SHIT');
        var thisObject = this;
        if (breakpoint == 'small'){
            if (currentViewed == id) {
                $('#current').css("max-height","0");
                currentViewed = 0;
                setTimeout(function() {
                        $('#current').remove();
                },1000);
            } else {
                if ($('#current').length > 0) {
                    $('#current').css("max-height","0");
                    setTimeout(function() {
                        $('#current').remove();
                        showInfoSmall(thisObject, events, id);
                    },1000);
                } else {
                    showInfoSmall(thisObject, events, id);
                }
            }
            
        }
    
        /*setTimeout(function() {
            $('#current').css("max-height", "1000px");
        },0);*/
    });

</script>