config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root 'feed_events#index'
  
  resources :user_profiles
  resources :genres
  resources :events
  resources :comments
  
  post 'event_response', to: 'user_event_responses#update', as: :event_response
  
  get 'reactivate_account', to: 'user_profiles#reactivate_account', as: :reactivate_account
  get 'activate_user', to: 'user_profiles#activate_user', as: :activate_user
  get 'remove_event', to: 'events#remove_from_feed', as: :remove_event
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    
    #Model Associations
    belongs_to :creator, :class_name => "User", :foreign_key => "creator_id"
    belongs_to :event
    
    validates :comment, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
    
    # Model associations
    belongs_to :creator, :class_name => "User", :foreign_key => "creator_id"
    belongs_to :location
    accepts_nested_attributes_for :location
    has_many :location_components, through: :location
    accepts_nested_attributes_for :location_components
    has_and_belongs_to_many :genres, :association_foreign_key => "genre_name"
    has_many :events_images
    accepts_nested_attributes_for :events_images
    has_many :images, through: :events_images
    has_many :user_removed_events
    has_many :comments
    
    has_one :feed_event
    
    # ActiveRecord validations
    validates :name, presence: true, length: { minimum: 1, maximum: 255 }
    validates :description, presence: true, length: { minimum: 1 }
    validates :start_datetime, presence: true
    validates_datetime :start_datetime, :after => :now
    validates_datetime :end_datetime, :after => :start_datetime
end

app/models/event_log.rb
class EventLog < ActiveRecord::Base
    
    # Model associations
    belongs_to :user
    belongs_to :event
    
    # ActiveRecord validations
    validates :description, presence: true, length: { minimum: 1 }
end

app/models/event_response.rb
class EventResponse < ActiveRecord::Base
    has_one :user_event_response
end

app/models/events_genre.rb
class EventsGenre < ActiveRecord::Base
    # Activemodel Associations
    belongs_to :event
    belongs_to :genre, :foreign_key => "genre_name"
end

app/models/events_image.rb
class EventsImage < ActiveRecord::Base
    
    # Model Associations
    belongs_to :event
    belongs_to :image
    accepts_nested_attributes_for :image
    
    # ActiveRecord validations
    validates :feature_image, presence: true
end

app/models/feed_event.rb
class FeedEvent < ActiveRecord::Base
   self.primary_key = "event_id"
   
   belongs_to :event
end

app/models/friend_connection.rb
class FriendConnection < ActiveRecord::Base
    
    # Sets composite primary key
    self.primary_keys = :user_id, :friend_id
    
    # Model associations
    belongs_to :user
    belongs_to :friend, :class_name => "User", :foreign_key => "friend_id"
    
    # Activerecord Validations
end

app/models/genre.rb
class Genre < ActiveRecord::Base
    # Setting domain specific primary key
  self.primary_key = :name
  
    # Model Associations
    has_and_belongs_to_many :users, :foreign_key => "genre_name"
    has_and_belongs_to_many :events, :foreign_key => "genre_name"
    belongs_to :creator, :class_name => "User", :foreign_key => "creator_id"
  
    # ActiveRecord validations
    
    
end

app/models/image.rb
class Image < ActiveRecord::Base
    
    # Model associations
    belongs_to :creator, :class_name => "User", :foreign_key => "creator_id"
    has_many :events, through: :events_images
    has_many :events_images
    
    # ActiveRecord validations
    validates :path, presence: true
end

app/models/location.rb
class Location < ActiveRecord::Base
    
    # Model associations
    has_many :user_profiles
    has_many :location_components
    has_many :events
    
    # ActiveRecord validation
    validates :lat, presence: true, numericality: true, length: { maximum: 12 }
    validates :lng, presence: true, numericality: true, length: { maximum: 13 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  # Model associations
  
    #UserProfile
  has_one :user_profile
  
    #Location
  has_one :location, :through => :user_profiles
  has_many :location_components, :through => :locations
  
    # FriendConnection
  has_many :friend_connections
  has_many :friends, :through => :friend_connections
  has_many :inverse_friend_connections, :class_name => "FriendConnection", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friend_connections, :source => :user
  
    # UserLog
  has_many :user_logs
  
    # Image
  has_many :images, :foreign_key => "creator_id"
  
    # UserProfileImage
  has_many :user_profile_images
  
    # Event
  has_many :events, :foreign_key => "creator_id"
  has_many :user_removed_events
    
    #EventLog
  has_many :event_logs
  
    #Genre
  has_and_belongs_to_many :genres, :association_foreign_key => "genre_name"
  has_many :genres, :foreign_key => "creator_id"
  
    #Comments
  has_many :comments, :foreign_key => "creator_id"
  
end

app/models/user_log.rb
class UserLog < ActiveRecord::Base
    
    # Model associations
    belongs_to :user
    
    # ActiveRecord validations
    validates :description, presence: true, length: { minimum: 1 }
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  
  # Setting domain specific primary key
  self.primary_key = 'user_id'
  
  # Model associations
  belongs_to :user
  belongs_to :location
  accepts_nested_attributes_for :location
  
  # ActiveRecord Validations
    validates :first_name, presence: true, length: { minimum: 1, maximum: 255 }
    validates :last_name, presence: true, length: { minimum: 1, maximum: 255 }
    validates :birth_date, presence: true
    validates_datetime :birth_date, :before => :now
    validates_datetime :birth_date, :after => lambda { 150.years.ago }
end

app/models/users_genre.rb
class UsersGenre < ActiveRecord::Base
    # Activemodel Associations
    belongs_to :user
    belongs_to :genre, :foreign_key => "genre_name"
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/feed_helper.rb
module FeedHelper
    def genre_display(genres)
        count = genres.count
        
        case count
            when 0
                genre_display = '<p>There are no genres playing</p>'.html_safe
            when 1 
                genre_display = "<p><span class=\"highlight\">#{genres.first.name}</span> is playing</p>".html_safe
            else
                #tiny display
                genre_display = "<p class=\"tiny genres\">#{count} genres playing</p>".html_safe
                
                #small and medium display
                genre_display += "<p class=\"small genres\"><span class=\"highlight\">#{genres.first.name}</span> and <span class=\"highlight\">#{count - 1} other genres</span> are playing</p>".html_safe
                
                #large display
                genre_display += '<p class="large genres">'.html_safe
                genres[1..-2].each do |genre|
                   genre_display += "<span class=\"highlight\">#{genre.name}</span>, ".html_safe
                end
                genre_display += "and <span class=\"highlight\">#{genres[-1].name}</span> are playing</p>".html_safe
        end
    end
    
    def over_eighteen_display(over_eighteen)
       over_eighteen_display = '<span class="over-eighteen medium">18+</span>'.html_safe if over_eighteen == true
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        Footer
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav>
        <div class="container">
          <% if user_signed_in? %>
              <%= link_to root_path do %>
                <%= image_tag('icons/logo.png') %>
                <span>Revolution</span>
              <% end %>
              <ul>
                <li>
                  <%= link_to root_path do %>
                    <%= image_tag('icons/events.png') %>
                    <span>Pit List</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_event_path do %>
                    <%= image_tag('icons/create.png') %>
                    <span>Create Event</span>
                  <% end %>
                </li>
                <li class="dropdown">
                  <a href="#">
                    <%= image_tag('icons/settings.png') %>
                    <span>Account</span>
                  </a>
                  <ul>
                    <li>
                      <%= link_to user_profile_path(current_user) do %>
                      <span>View Profile</span>
                      <% end %>
                    </li>
                    <div class="horizontal-divider"></div>
                    <li>
                      <%= link_to edit_user_profile_path(current_user) do %>
                      <span>Edit Profile</span>
                      <% end %>
                    </li>
                    <div class="horizontal-divider"></div>
                    <li>
                      <%= link_to(destroy_user_session_path, :method => :delete) do %>
                        <span>Log Out</span>
                      <% end %>
                    </li>
                  </ul>
                </li>
              </ul>
            <% else %>
              <%= image_tag('icons/logo.png') %>
            <% end %>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false" type="text/javascript"></script>
</head>
<body>
  
  <%= render 'layouts/header' %>

  <%= yield %>
  
  <%= render 'layouts/footer' %>
  
</body>
</html>